<?php
return [
    'employees',
    'photoGallery',
    'videoGallery',
    'contactUs',
    'bill',
    'faq',
    'links',
    'audioGallery',
    'subDivision',
    'allExEmployee',
    'exEmployee',
    'exChief',
    'lawsuit',
    'contractProgress',
    'totalProgress',
    'currentContract_praganna',
    'currentContract_badkapath',
    'finishedContract_badkapath',
    'finishedContract_praganna',
    'workPlan_progress',
    'committee',

];
