<?php
return [
    'employees',
    'photoGallery',
    'videoGallery',
    'contactUs',
    'bill',
    'faq',
    'links',
    'audioGallery',
    'subDivision',
    'allExEmployee',
    'exEmployee',
    'exChief',
    'lawsuit',
    'contractProgress',
    'totalProgress',
    'finishedContract',
    'currentContract'
];
